# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chatserver.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63hatserver.proto\x12\x06server\"8\n\x14\x43onnectToChatRequest\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x10\n\x08receiver\x18\x02 \x01(\t\"\'\n\x15\x43onnectToChatResponse\x12\x0e\n\x06\x61\x63\x63\x65pt\x18\x01 \x01(\x05\"G\n\x12SendMessageRequest\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x10\n\x08receiver\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"&\n\x13SendMessageResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\")\n\x15ReceiveMessageRequest\x12\x10\n\x08receiver\x18\x01 \x01(\t\"~\n\x16ReceiveMessageResponse\x12\x38\n\x08messages\x18\x01 \x03(\x0b\x32&.server.ReceiveMessageResponse.Message\x1a*\n\x07Message\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1d\n\x1bSubscribeToGroupChatRequest\"/\n\x1cSubscribeToGroupChatResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xde\x02\n\nChatServer\x12H\n\x0bSendMessage\x12\x1a.server.SendMessageRequest\x1a\x1b.server.SendMessageResponse\"\x00\x12Q\n\x0eReceiveMessage\x12\x1d.server.ReceiveMessageRequest\x1a\x1e.server.ReceiveMessageResponse\"\x00\x12N\n\rConnectToChat\x12\x1c.server.ConnectToChatRequest\x1a\x1d.server.ConnectToChatResponse\"\x00\x12\x63\n\x14SubscribeToGroupChat\x12#.server.SubscribeToGroupChatRequest\x1a$.server.SubscribeToGroupChatResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chatserver_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CONNECTTOCHATREQUEST']._serialized_start=28
  _globals['_CONNECTTOCHATREQUEST']._serialized_end=84
  _globals['_CONNECTTOCHATRESPONSE']._serialized_start=86
  _globals['_CONNECTTOCHATRESPONSE']._serialized_end=125
  _globals['_SENDMESSAGEREQUEST']._serialized_start=127
  _globals['_SENDMESSAGEREQUEST']._serialized_end=198
  _globals['_SENDMESSAGERESPONSE']._serialized_start=200
  _globals['_SENDMESSAGERESPONSE']._serialized_end=238
  _globals['_RECEIVEMESSAGEREQUEST']._serialized_start=240
  _globals['_RECEIVEMESSAGEREQUEST']._serialized_end=281
  _globals['_RECEIVEMESSAGERESPONSE']._serialized_start=283
  _globals['_RECEIVEMESSAGERESPONSE']._serialized_end=409
  _globals['_RECEIVEMESSAGERESPONSE_MESSAGE']._serialized_start=367
  _globals['_RECEIVEMESSAGERESPONSE_MESSAGE']._serialized_end=409
  _globals['_SUBSCRIBETOGROUPCHATREQUEST']._serialized_start=411
  _globals['_SUBSCRIBETOGROUPCHATREQUEST']._serialized_end=440
  _globals['_SUBSCRIBETOGROUPCHATRESPONSE']._serialized_start=442
  _globals['_SUBSCRIBETOGROUPCHATRESPONSE']._serialized_end=489
  _globals['_CHATSERVER']._serialized_start=492
  _globals['_CHATSERVER']._serialized_end=842
# @@protoc_insertion_point(module_scope)
