# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: insultingServer.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15insultingServer.proto\x1a\x1bgoogle/protobuf/empty.proto\"*\n\x06Insult\x12\x0e\n\x06insult\x18\x01 \x01(\t\x12\x10\n\x08severity\x18\x02 \x01(\x02\"\x18\n\x07Insults\x12\r\n\x05value\x18\x01 \x03(\t\"!\n\nInsultName\x12\x13\n\x0binsult_name\x18\x01 \x01(\t\"\x19\n\x08Severity\x12\r\n\x05value\x18\x01 \x01(\x02\x32\xd0\x01\n\x10InsultingService\x12\x30\n\nGetInsults\x12\x16.google.protobuf.Empty\x1a\x08.Insults\"\x00\x12.\n\tAddInsult\x12\x07.Insult\x1a\x16.google.protobuf.Empty\"\x00\x12\x31\n\x08InsultMe\x12\x16.google.protobuf.Empty\x1a\x0b.InsultName\"\x00\x12\'\n\x0bGetSeverity\x12\x0b.InsultName\x1a\t.Severity\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'insultingServer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_INSULT']._serialized_start=54
  _globals['_INSULT']._serialized_end=96
  _globals['_INSULTS']._serialized_start=98
  _globals['_INSULTS']._serialized_end=122
  _globals['_INSULTNAME']._serialized_start=124
  _globals['_INSULTNAME']._serialized_end=157
  _globals['_SEVERITY']._serialized_start=159
  _globals['_SEVERITY']._serialized_end=184
  _globals['_INSULTINGSERVICE']._serialized_start=187
  _globals['_INSULTINGSERVICE']._serialized_end=395
# @@protoc_insertion_point(module_scope)
