# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nameserver.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10nameserver.proto\x12\x06server\"E\n\x0fRegisterRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x12\n\nip_address\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\"#\n\x10RegisterResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"!\n\rLookupRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"C\n\x0eLookupResponse\x12\x12\n\nip_address\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\x12\x0f\n\x07message\x18\x03 \x01(\t\"\x16\n\x14\x44iscoverChatsRequest\"&\n\x15\x44iscoverChatsResponse\x12\r\n\x05\x63hats\x18\x01 \x03(\t\"\x1a\n\x18JoinInsultChannelRequest\",\n\x19JoinInsultChannelResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xb4\x02\n\nNameServer\x12?\n\x08Register\x12\x17.server.RegisterRequest\x1a\x18.server.RegisterResponse\"\x00\x12\x39\n\x06Lookup\x12\x15.server.LookupRequest\x1a\x16.server.LookupResponse\"\x00\x12N\n\rDiscoverChats\x12\x1c.server.DiscoverChatsRequest\x1a\x1d.server.DiscoverChatsResponse\"\x00\x12Z\n\x11JoinInsultChannel\x12 .server.JoinInsultChannelRequest\x1a!.server.JoinInsultChannelResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nameserver_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REGISTERREQUEST']._serialized_start=28
  _globals['_REGISTERREQUEST']._serialized_end=97
  _globals['_REGISTERRESPONSE']._serialized_start=99
  _globals['_REGISTERRESPONSE']._serialized_end=134
  _globals['_LOOKUPREQUEST']._serialized_start=136
  _globals['_LOOKUPREQUEST']._serialized_end=169
  _globals['_LOOKUPRESPONSE']._serialized_start=171
  _globals['_LOOKUPRESPONSE']._serialized_end=238
  _globals['_DISCOVERCHATSREQUEST']._serialized_start=240
  _globals['_DISCOVERCHATSREQUEST']._serialized_end=262
  _globals['_DISCOVERCHATSRESPONSE']._serialized_start=264
  _globals['_DISCOVERCHATSRESPONSE']._serialized_end=302
  _globals['_JOININSULTCHANNELREQUEST']._serialized_start=304
  _globals['_JOININSULTCHANNELREQUEST']._serialized_end=330
  _globals['_JOININSULTCHANNELRESPONSE']._serialized_start=332
  _globals['_JOININSULTCHANNELRESPONSE']._serialized_end=376
  _globals['_NAMESERVER']._serialized_start=379
  _globals['_NAMESERVER']._serialized_end=687
# @@protoc_insertion_point(module_scope)
