# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import nameserver_pb2 as nameserver__pb2


class NameServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/server.NameServer/Register',
                request_serializer=nameserver__pb2.RegisterRequest.SerializeToString,
                response_deserializer=nameserver__pb2.RegisterResponse.FromString,
                )
        self.Lookup = channel.unary_unary(
                '/server.NameServer/Lookup',
                request_serializer=nameserver__pb2.LookupRequest.SerializeToString,
                response_deserializer=nameserver__pb2.LookupResponse.FromString,
                )
        self.DiscoverChats = channel.unary_unary(
                '/server.NameServer/DiscoverChats',
                request_serializer=nameserver__pb2.DiscoverChatsRequest.SerializeToString,
                response_deserializer=nameserver__pb2.DiscoverChatsResponse.FromString,
                )
        self.JoinInsultChannel = channel.unary_unary(
                '/server.NameServer/JoinInsultChannel',
                request_serializer=nameserver__pb2.JoinInsultChannelRequest.SerializeToString,
                response_deserializer=nameserver__pb2.JoinInsultChannelResponse.FromString,
                )


class NameServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Lookup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DiscoverChats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def JoinInsultChannel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NameServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=nameserver__pb2.RegisterRequest.FromString,
                    response_serializer=nameserver__pb2.RegisterResponse.SerializeToString,
            ),
            'Lookup': grpc.unary_unary_rpc_method_handler(
                    servicer.Lookup,
                    request_deserializer=nameserver__pb2.LookupRequest.FromString,
                    response_serializer=nameserver__pb2.LookupResponse.SerializeToString,
            ),
            'DiscoverChats': grpc.unary_unary_rpc_method_handler(
                    servicer.DiscoverChats,
                    request_deserializer=nameserver__pb2.DiscoverChatsRequest.FromString,
                    response_serializer=nameserver__pb2.DiscoverChatsResponse.SerializeToString,
            ),
            'JoinInsultChannel': grpc.unary_unary_rpc_method_handler(
                    servicer.JoinInsultChannel,
                    request_deserializer=nameserver__pb2.JoinInsultChannelRequest.FromString,
                    response_serializer=nameserver__pb2.JoinInsultChannelResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'server.NameServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NameServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/server.NameServer/Register',
            nameserver__pb2.RegisterRequest.SerializeToString,
            nameserver__pb2.RegisterResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Lookup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/server.NameServer/Lookup',
            nameserver__pb2.LookupRequest.SerializeToString,
            nameserver__pb2.LookupResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DiscoverChats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/server.NameServer/DiscoverChats',
            nameserver__pb2.DiscoverChatsRequest.SerializeToString,
            nameserver__pb2.DiscoverChatsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def JoinInsultChannel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/server.NameServer/JoinInsultChannel',
            nameserver__pb2.JoinInsultChannelRequest.SerializeToString,
            nameserver__pb2.JoinInsultChannelResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
